# Generated by Django 2.0.8 on 2018-09-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180914_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumo',
            name='imgs',
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
