# Generated by Django 2.0.8 on 2018-09-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180914_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('img', models.ImageField(upload_to='blog/img/')),
            ],
        ),
        migrations.AddField(
            model_name='resumo',
            name='imgs',
            field=models.ManyToManyField(blank=True, to='blog.Imagem'),
        ),
    ]
