# Generated by Django 2.0.8 on 2018-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180914_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='blog/posts/', verbose_name='imagem'),
        ),
    ]
