# Generated by Django 2.0.8 on 2018-09-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumo',
            old_name='subtitulo',
            new_name='datas',
        ),
    ]
