# Generated by Django 2.0.8 on 2018-09-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180918_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='imgs',
            field=models.ManyToManyField(blank=True, to='blog.Imagem', verbose_name='imagens'),
        ),
    ]
