# Generated by Django 2.0.8 on 2018-10-19 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import o_t.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('01', 'o_t'), ('02', 'organização'), ('03', 'patrocínio'), ('04', 'apoio')], max_length=20, null=True)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('arquivo', models.FileField(upload_to=o_t.models.arquivos_filepath)),
                ('altura', models.CharField(default='100', max_length=4)),
                ('en', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='BlocoRespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nome_en', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('data1', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=20)),
                ('titulo', models.TextField(blank=True)),
                ('datas', models.TextField(blank=True)),
                ('texto', models.TextField(blank=True)),
                ('titulo_en', models.TextField(blank=True)),
                ('datas_en', models.TextField(blank=True)),
                ('texto_en', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nascimento', models.DateField(verbose_name='nascimento')),
                ('cpf', models.CharField(max_length=30, unique=True, verbose_name='CPF/CNPJ')),
                ('celular', models.CharField(max_length=20, verbose_name='celular')),
                ('rua', models.CharField(max_length=60, verbose_name='endereço')),
                ('complemento', models.CharField(blank=True, max_length=20, verbose_name='complemento')),
                ('bairro', models.CharField(max_length=20, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=20, verbose_name='cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='estado')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('pais', models.CharField(max_length=20, verbose_name='país')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=70, null=True, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('pergunta_en', models.TextField(blank=True)),
                ('resposta_en', models.TextField(blank=True)),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('publicar', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['data0'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('arquivo', models.ImageField(upload_to=o_t.models.imagem_filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=70, null=True, verbose_name='sobrenome')),
                ('area', models.CharField(choices=[('01', 'Arquitetura'), ('02', 'Artes Visuais'), ('03', 'Artes Performáticas'), ('04', 'Design'), ('05', 'Paisagismo')], max_length=20, verbose_name='área')),
                ('termos', models.BooleanField()),
                ('codigo', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('finalizada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['data0'],
            },
        ),
        migrations.CreateModel(
            name='Juri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('site', models.URLField(blank=True)),
                ('bio', models.TextField()),
                ('bio_en', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('titulo_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('texto', models.TextField()),
                ('texto_en', models.TextField(blank=True)),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('data1', models.DateTimeField(blank=True, null=True, verbose_name='publicação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data1', '-data0'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('texto', models.TextField(blank=True)),
                ('texto_en', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('consulta', models.TextField(verbose_name='consulta')),
                ('pergunta', models.TextField(blank=True, null=True)),
                ('pergunta_en', models.TextField(blank=True, null=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('resposta_en', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bloco', models.ForeignKey(blank=True, default=o_t.models.set_rascunho, on_delete=models.SET(o_t.models.set_rascunho), to='o_t.BlocoRespostas')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('palafita', models.CharField(choices=[('01', '01. Cônsul Walter 425: palafita-pomar'), ('02', '02. Cônsul Walter 437: palafita-caverna'), ('03', '03. Cônsul Walter 483: palafita-empena'), ('04', '04. Cônsul Walter 511: palafita-indiscreta'), ('05', '05. Teresa Mota Valadares 76: palafita-caleidoscópica'), ('06', '06. Fidélis Martins 173: palafita-esbelta'), ('07', '07. Maria Heilbuth Surete 1223: palafita-dos-cachorros'), ('08', '08. Maria Heilbuth Surete 1159: palafita-comum'), ('09', '09. Maria Heilbuth Surete 1193: palafita-gigante-I'), ('10', '10. Maria Heilbuth Surete 1295: palafita-gigante-II')], max_length=2)),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('texto', models.TextField(blank=True, max_length=3000, verbose_name='descrição')),
                ('img', models.ImageField(blank=True, upload_to=o_t.models.inscricao_filepath, verbose_name='imagem')),
                ('arquivo', models.FileField(blank=True, upload_to=o_t.models.inscricao_filepath, verbose_name='arquivo')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=100, unique=True)),
                ('tag_en', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='nota',
            name='tags',
            field=models.ManyToManyField(blank=True, to='o_t.Tag'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Nota'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao'),
        ),
        migrations.AddField(
            model_name='dados',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='pagina',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='o_t.Cartaz'),
        ),
    ]
