# Generated by Django 2.0.8 on 2018-09-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('datas', models.TextField(blank=True)),
                ('texto', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='o_t/img/')),
            ],
        ),
        migrations.AddField(
            model_name='cartaz',
            name='imagens',
            field=models.ManyToManyField(blank=True, to='o_t.Imagem'),
        ),
    ]
