# Generated by Django 2.0.8 on 2018-10-19 14:01

from django.db import migrations, models
import o_t.models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=o_t.models.arquivos_filepath),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=o_t.models.arquivos_filepath),
        ),
    ]
