# Generated by Django 2.0.8 on 2018-10-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0002_auto_20181019_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='bloco',
        ),
        migrations.DeleteModel(
            name='BlocoRespostas',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
    ]
