# Generated by Django 2.0.8 on 2018-10-23 17:10

from django.db import migrations, models
import o_t.models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0003_auto_20181023_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoRespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nome_en', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('data1', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('pergunta_en', models.TextField(blank=True)),
                ('resposta_en', models.TextField(blank=True)),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('publicar', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['data0'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('consulta', models.TextField(verbose_name='consulta')),
                ('pergunta', models.TextField(blank=True, null=True)),
                ('pergunta_en', models.TextField(blank=True, null=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('resposta_en', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bloco', models.ForeignKey(blank=True, default=o_t.models.set_rascunho, on_delete=models.SET(o_t.models.set_rascunho), to='o_t.BlocoRespostas')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
