# Generated by Django 2.0.8 on 2018-09-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0003_auto_20180919_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
