# Generated by Django 2.0.8 on 2018-10-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0005_remove_inscricao_termos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='lang',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
