# Generated by Django 2.0.8 on 2018-10-30 00:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0006_pergunta_lang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagina',
        ),
        migrations.AlterModelOptions(
            name='juri',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='dados',
            name='pais',
            field=django_countries.fields.CountryField(default='BR', max_length=2),
        ),
    ]
