# Generated by Django 2.0.8 on 2018-09-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0006_auto_20180920_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='o_t/arquivos/')),
            ],
        ),
        migrations.CreateModel(
            name='Cartaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=50)),
                ('titulo', models.TextField(blank=True)),
                ('datas', models.TextField(blank=True)),
                ('texto', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='arquivo',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Cartaz'),
        ),
    ]
