# Generated by Django 2.0.8 on 2018-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0007_auto_20181029_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='bairro',
            field=models.CharField(max_length=30, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='estado',
            field=models.CharField(max_length=4, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='rua',
            field=models.CharField(max_length=100, verbose_name='endereço'),
        ),
    ]
