# Generated by Django 2.0.8 on 2018-09-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0007_auto_20180920_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('bio', models.TextField()),
            ],
        ),
    ]
