# Generated by Django 2.0.8 on 2018-10-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0008_auto_20181030_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='pais',
        ),
    ]
