# Generated by Django 2.0.8 on 2018-11-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0008_auto_20181101_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='palafita',
            field=models.CharField(choices=[('01', '01. Cônsul Walter 425: palafita-pomar'), ('02', '02. Cônsul Walter 437: palafita-caverna'), ('03', '03. Cônsul Walter 483: palafita-empena'), ('04', '04. Cônsul Walter 511: palafita-indiscreta'), ('05', '05. Teresa Mota Valadares 76: palafita-caleidoscópica'), ('06', '06. Fidélis Martins 173: palafita-esbelta'), ('07', '07. Maria Heilbuth Surete 1223: palafita-dos-cachorros'), ('08', '08. Maria Heilbuth Surete 1159: palafita-comum'), ('09', '09. Maria Heilbuth Surete 1193: palafita-gigante-I'), ('10', '10. Maria Heilbuth Surete 1295: palafita-gigante-II')], max_length=2, verbose_name='palafita'),
        ),
    ]
