# Generated by Django 2.0.8 on 2018-11-05 22:07

from django.db import migrations, models
import o_t.models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0009_auto_20181105_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=o_t.models.inscricao_filepath, validators=[o_t.models.validate_size], verbose_name='arquivo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='img',
            field=models.ImageField(blank=True, upload_to=o_t.models.inscricao_filepath, validators=[o_t.models.validate_size], verbose_name='imagem'),
        ),
    ]
