# Generated by Django 2.0.8 on 2018-09-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0009_auto_20180924_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
