# Generated by Django 2.0.8 on 2018-10-31 18:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0010_auto_20181031_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='cidade',
        ),
        migrations.AlterField(
            model_name='dados',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='o_t.Region'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='pais',
            field=models.ForeignKey(default='31', null=True, on_delete=django.db.models.deletion.SET_NULL, to='o_t.Country', verbose_name='país'),
        ),
    ]
