# Generated by Django 2.0.8 on 2018-09-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0010_nota_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('data1', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
