# Generated by Django 2.0.8 on 2018-11-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0010_auto_20181105_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='bairro',
        ),
    ]
