# Generated by Django 2.0.8 on 2018-09-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0011_pergunta_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
