# Generated by Django 2.0.8 on 2018-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0012_auto_20180924_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='data1',
        ),
        migrations.AddField(
            model_name='resposta',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
