# Generated by Django 2.0.8 on 2018-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0012_auto_20181031_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='celular',
            field=models.CharField(default='', max_length=20, verbose_name='celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados',
            name='cpf',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados',
            name='nascimento',
            field=models.DateField(default='2000-01-01', verbose_name='nascimento'),
            preserve_default=False,
        ),
    ]
