# Generated by Django 2.0.8 on 2018-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0013_auto_20181031_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='bairro',
            field=models.CharField(default='', max_length=30, verbose_name='bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados',
            name='cep',
            field=models.CharField(default='', max_length=15, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados',
            name='complemento',
            field=models.CharField(blank=True, max_length=20, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='dados',
            name='rua',
            field=models.CharField(default='', max_length=100, verbose_name='endereço'),
            preserve_default=False,
        ),
    ]
