# Generated by Django 2.0.8 on 2019-01-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0013_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('texto_en', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.CharField(blank=True, choices=[('ok', 'aprovado'), ('no', 'desaprovado')], max_length=2, verbose_name='seleção')),
                ('titulo', models.CharField(blank=True, max_length=220)),
                ('texto', models.TextField(blank=True)),
                ('titulo_en', models.CharField(blank=True, max_length=220)),
                ('texto_en', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['finalizada', 'data0']},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-data1']},
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('01', 'o_t'), ('02', 'organização'), ('03', 'patrocínio'), ('04', 'apoio institucional'), ('05', 'parceiro de mídia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='selecao',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao'),
        ),
    ]
