# Generated by Django 2.0.8 on 2018-09-25 18:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0013_auto_20180925_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('celular', models.CharField(max_length=16)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=60)),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('area', models.CharField(max_length=50, verbose_name='área de atuação profissional')),
                ('termos', models.BooleanField()),
            ],
            options={
                'ordering': ['data0'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='titulo do projeto')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('texto', models.TextField(verbose_name='descrição do projeto')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao')),
            ],
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['?']},
        ),
        migrations.AddField(
            model_name='equipe',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao'),
        ),
        migrations.AddField(
            model_name='dados',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao'),
        ),
    ]
