# Generated by Django 2.0.8 on 2018-10-31 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0014_auto_20181031_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='pais',
            field=models.ForeignKey(default='31', null=True, on_delete=django.db.models.deletion.SET_NULL, to='o_t.Country', verbose_name='país'),
        ),
    ]
