# Generated by Django 2.0.8 on 2019-01-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0014_auto_20190131_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='ok',
            field=models.CharField(choices=[('ok', 'aprovado'), ('no', 'desaprovado')], max_length=2, verbose_name='seleção'),
        ),
    ]
