# Generated by Django 2.0.8 on 2018-09-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0015_auto_20180925_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='rua',
        ),
    ]
