# Generated by Django 2.0.8 on 2018-10-31 21:11

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0015_dados_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='country', default='1', on_delete=django.db.models.deletion.CASCADE, to='o_t.Region'),
            preserve_default=False,
        ),
    ]
