# Generated by Django 2.0.8 on 2019-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0016_auto_20190201_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='texto_en',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='titulo_en',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='traducao',
            field=models.CharField(choices=[('-', '---'), ('pt', 'português'), ('en', 'inglês')], default='-', max_length=2, verbose_name='tradução'),
        ),
        migrations.AlterField(
            model_name='criterios',
            name='texto_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
