# Generated by Django 2.0.8 on 2018-10-31 21:11

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0016_dados_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='cidade',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='region', default='1', on_delete=django.db.models.deletion.CASCADE, to='o_t.City'),
            preserve_default=False,
        ),
    ]
