# Generated by Django 2.0.8 on 2018-11-01 14:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0017_dados_cidade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.AlterField(
            model_name='dados',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='estado',
            field=models.CharField(max_length=4, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='pais',
            field=django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='país'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
