# Generated by Django 2.0.8 on 2018-09-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0017_auto_20180925_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.DecimalField(decimal_places=0, max_digits=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('celular', models.DecimalField(decimal_places=0, max_digits=13)),
                ('cep', models.DecimalField(decimal_places=0, max_digits=8)),
                ('rua', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao')),
            ],
        ),
    ]
