# Generated by Django 2.0.8 on 2019-02-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0018_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='criterio',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
