# Generated by Django 2.0.8 on 2018-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0018_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='pais',
            field=models.CharField(default='brasil', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dados',
            name='celular',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='dados',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='dados',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
