# Generated by Django 2.0.8 on 2018-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0019_auto_20180926_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['data0']},
        ),
        migrations.AlterField(
            model_name='dados',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='complemento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dados',
            name='nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
