# Generated by Django 2.0.8 on 2019-02-01 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('o_t', '0019_auto_20190201_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=2, verbose_name='nota')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Criterios')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoJuri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s2', models.BooleanField(default=False, verbose_name='favorito')),
                ('texto', models.TextField(blank=True, verbose_name='comentário')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Inscricao')),
                ('juri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notas', models.ManyToManyField(to='o_t.Avaliacao')),
            ],
        ),
    ]
