# Generated by Django 2.0.8 on 2019-02-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0020_avaliacao_avaliacaojuri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='criterio',
        ),
        migrations.AlterModelOptions(
            name='criterios',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='avaliacaojuri',
            name='notas',
        ),
        migrations.AlterField(
            model_name='avaliacaojuri',
            name='s2',
            field=models.BooleanField(default=False, verbose_name='♥'),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
