# Generated by Django 2.0.8 on 2018-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0020_auto_20180926_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoRespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('data1', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['-data']},
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='ok',
        ),
    ]
