# Generated by Django 2.0.8 on 2018-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0021_auto_20180926_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
