# Generated by Django 2.0.8 on 2019-02-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0022_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaojuri',
            name='media',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='avaliacaojuri',
            name='texto',
            field=models.TextField(blank=True, default='', verbose_name='comentário'),
        ),
        migrations.AlterField(
            model_name='criterios',
            name='texto',
            field=models.CharField(max_length=300, verbose_name='pt'),
        ),
        migrations.AlterField(
            model_name='criterios',
            name='texto_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='en'),
        ),
    ]
