# Generated by Django 2.0.8 on 2018-09-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0022_pergunta_ok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.AlterModelOptions(
            name='blocorespostas',
            options={'ordering': ['data0']},
        ),
    ]
