# Generated by Django 2.0.8 on 2019-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0023_auto_20190204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaojuri',
            name='media',
            field=models.FloatField(default=0),
        ),
    ]
