# Generated by Django 2.0.8 on 2018-09-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0023_auto_20180926_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('bloco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='o_t.BlocoRespostas')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='o_t.Pergunta')),
            ],
            options={
                'ordering': ['data0'],
            },
        ),
    ]
