# Generated by Django 2.0.8 on 2018-09-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0024_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='bloco',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='consulta',
        ),
    ]
