# Generated by Django 2.0.8 on 2019-02-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0024_auto_20190204_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='media',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='avaliacaojuri',
            name='texto',
            field=models.TextField(blank=True, default='', verbose_name='ps'),
        ),
    ]
