# Generated by Django 2.0.8 on 2019-02-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0025_auto_20190206_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='s2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avaliacaojuri',
            name='texto',
            field=models.TextField(blank=True, default='', verbose_name='comentário'),
        ),
    ]
