# Generated by Django 2.0.8 on 2018-09-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0029_auto_20180926_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='consulta',
        ),
    ]
