# Generated by Django 2.0.8 on 2018-09-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0030_remove_resposta_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='consulta',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='o_t.Pergunta'),
            preserve_default=False,
        ),
    ]
