# Generated by Django 2.0.8 on 2018-09-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0031_resposta_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='consulta',
        ),
    ]
