# Generated by Django 2.0.8 on 2018-09-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0033_auto_20180926_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('data0', models.DateTimeField(auto_now_add=True)),
                ('publicar', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['data0'],
            },
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='bloco',
        ),
        migrations.AlterModelOptions(
            name='blocorespostas',
            options={},
        ),
        migrations.AddField(
            model_name='pergunta',
            name='pergunta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
