# Generated by Django 2.0.8 on 2018-09-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0034_auto_20180927_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
