# Generated by Django 2.0.8 on 2018-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0037_auto_20181003_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('o_t', 'o_t'), ('patrocinio', 'patrocinio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='area',
            field=models.CharField(choices=[('arquitetura', 'arquitetura'), ('design', 'design')], max_length=20, verbose_name='área'),
        ),
        migrations.DeleteModel(
            name='LogoTipo',
        ),
    ]
