# Generated by Django 2.0.8 on 2018-10-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0038_auto_20181004_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='sobrenome',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='area',
            field=models.CharField(choices=[('arquitetura', 'Arquitetura'), ('artesV', 'Artes Visuais'), ('artesP', 'Artes Performáticas'), ('design', 'Design'), ('paisagismo', 'Paisagismo')], max_length=20, verbose_name='área de atuação profissional'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
