# Generated by Django 2.0.8 on 2018-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0039_auto_20181009_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='rg',
        ),
        migrations.AddField(
            model_name='equipe',
            name='sobrenome',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='dados',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dados',
            name='cep',
            field=models.CharField(max_length=15, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='cpf',
            field=models.CharField(max_length=30, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='rua',
            field=models.CharField(max_length=60, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='area',
            field=models.CharField(choices=[('arquitetura', 'Arquitetura'), ('artesV', 'Artes Visuais'), ('artesP', 'Artes Performáticas'), ('design', 'Design'), ('paisagismo', 'Paisagismo')], max_length=20, verbose_name='área'),
        ),
    ]
