# Generated by Django 2.0.8 on 2018-10-09 20:22

from django.db import migrations, models
import o_t.models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0040_auto_20181009_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prancha',
            name='inscricao',
        ),
        migrations.AddField(
            model_name='projeto',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=o_t.models.inscricao_filepath),
        ),
        migrations.AddField(
            model_name='projeto',
            name='palafita',
            field=models.CharField(choices=[('01', '01. Cônsul Walter 425: palafita-pomar'), ('02', '02. Cônsul Walter 437: palafita-caverna'), ('03', '03. Cônsul Walter 483: palafita-empena'), ('04', '04. Cônsul Walter 511: palafita-indiscreta'), ('05', '05. Teresa Mota Valadares 76: palafita-caleidoscópica'), ('06', '06. Fidélis Martins 173: palafita-esbelta'), ('07', '07. Maria Heilbuth Surete 1223: palafita-dos-cachorros'), ('08', '08. Maria Heilbuth Surete 1159: palafita-comum'), ('09', '09. Maria Heilbuth Surete 1193: palafita-gigante-I'), ('10', '10. Maria Heilbuth Surete 1295: palafita-gigante-II')], default='01', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='texto',
            field=models.TextField(blank=True, max_length=3000, verbose_name='descrição'),
        ),
        migrations.DeleteModel(
            name='Prancha',
        ),
    ]
