# Generated by Django 2.0.8 on 2018-10-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0041_auto_20181009_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
