# Generated by Django 2.0.8 on 2018-10-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0042_inscricao_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaz',
            name='datas_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cartaz',
            name='texto_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cartaz',
            name='titulo_en',
            field=models.TextField(blank=True),
        ),
    ]
