# Generated by Django 2.0.8 on 2018-10-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0043_auto_20181011_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='juri',
            name='bio_en',
            field=models.TextField(blank=True),
        ),
    ]
