# Generated by Django 2.0.8 on 2018-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0044_juri_bio_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pergunta_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='resposta_en',
            field=models.TextField(blank=True),
        ),
    ]
