# Generated by Django 2.0.8 on 2018-10-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0045_auto_20181011_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='ok',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
