# Generated by Django 2.0.8 on 2018-10-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0046_auto_20181015_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='finalizado',
            new_name='finalizada',
        ),
    ]
