# Generated by Django 2.0.8 on 2018-10-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0048_auto_20181015_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blocorespostas',
            name='nome_en',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('o_t', 'o_t'), ('organizacao', 'organização'), ('patrocinio', 'patrocínio'), ('apoio', 'apoio')], max_length=20, null=True),
        ),
    ]
