# Generated by Django 2.0.8 on 2018-10-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0050_auto_20181015_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='altura',
            field=models.CharField(default='100', max_length=4),
        ),
    ]
