# Generated by Django 2.0.8 on 2018-10-16 18:42

from django.db import migrations, models
import django.db.models.deletion
import o_t.models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0051_arquivo_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('arquivo', models.ImageField(upload_to=o_t.models.imagem_filepath)),
            ],
        ),
        migrations.RemoveField(
            model_name='nota',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='slug',
        ),
        migrations.AddField(
            model_name='nota',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='texto_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blocorespostas',
            name='nome_en',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='imagem',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_t.Nota'),
        ),
    ]
