# Generated by Django 2.0.8 on 2018-10-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0052_auto_20181016_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='slug_en',
        ),
    ]
