# Generated by Django 2.0.8 on 2018-10-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0055_nota_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=100, unique=True)),
                ('tag_en', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='tags',
            field=models.ManyToManyField(to='o_t.Tag'),
        ),
    ]
