# Generated by Django 2.0.8 on 2018-10-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0056_auto_20181016_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('texto', models.TextField(blank=True)),
                ('texto_en', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cartaz',
            name='pagina',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tags',
            field=models.ManyToManyField(blank=True, to='o_t.Tag'),
        ),
    ]
