# Generated by Django 2.0.8 on 2018-10-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0057_auto_20181016_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
