# Generated by Django 2.0.8 on 2018-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0058_auto_20181017_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_en',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
