# Generated by Django 2.0.8 on 2018-10-18 16:07

from django.db import migrations, models
import o_t.models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0060_auto_20181017_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='bairro',
            field=models.CharField(max_length=20, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='celular',
            field=models.CharField(max_length=20, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='cidade',
            field=models.CharField(max_length=20, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='complemento',
            field=models.CharField(blank=True, max_length=20, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='nascimento',
            field=models.DateField(verbose_name='nascimento'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='pais',
            field=models.CharField(max_length=20, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='sobrenome',
            field=models.CharField(max_length=70, null=True, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e_mail'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='sobrenome',
            field=models.CharField(max_length=70, null=True, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='consulta',
            field=models.TextField(verbose_name='consulta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=o_t.models.inscricao_filepath, verbose_name='arquivo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='img',
            field=models.ImageField(blank=True, upload_to=o_t.models.inscricao_filepath, verbose_name='imagem'),
        ),
    ]
