# Generated by Django 2.0.8 on 2018-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_t', '0062_auto_20181018_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocorespostas',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
